"""schema

Revision ID: f60f71918573
Revises: 001_extensions
Create Date: 2026-05-30 09:45:51.952350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'f60f71918573'
down_revision: Union[str, None] = '001_extensions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environmental_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_tile', sa.String(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('aqi', sa.Integer(), nullable=True),
    sa.Column('pm25', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('soil_ph', sa.Float(), nullable=True),
    sa.Column('soil_type', sa.String(), nullable=True),
    sa.Column('sunlight_hours', sa.Float(), nullable=True),
    sa.Column('rainfall', sa.Float(), nullable=True),
    sa.Column('urban_rural_class', sa.Enum('URBAN', 'SUBURBAN', 'RURAL', name='urbanruralclass'), nullable=True),
    sa.Column('pollution_severity_class', sa.Enum('GOOD', 'MODERATE', 'UNHEALTHY_SENSITIVE', 'UNHEALTHY', 'VERY_UNHEALTHY', 'HAZARDOUS', name='pollutionseverityclass'), nullable=True),
    sa.Column('climate_zone', sa.String(), nullable=True),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ttl_seconds', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_environmental_profiles_location_tile', 'environmental_profiles', ['location_tile'], unique=False)
    op.create_table('news_feed_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content_summary', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('ENVIRONMENT', 'COMMUNITY', 'TIPS', 'ALERTS', name='newscategory'), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('location_scope', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plant_species',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('common_name', sa.String(), nullable=False),
    sa.Column('scientific_name', sa.String(), nullable=False),
    sa.Column('genus', sa.String(), nullable=False),
    sa.Column('family', sa.String(), nullable=False),
    sa.Column('co2_absorption_rate', sa.Float(), nullable=True),
    sa.Column('pm25_absorption_rate', sa.Float(), nullable=True),
    sa.Column('voc_absorption_rate', sa.Float(), nullable=True),
    sa.Column('toxicity_level', sa.Enum('NONE', 'LOW', 'MEDIUM', 'HIGH', name='toxicitylevel'), nullable=False),
    sa.Column('allergen_risk', sa.Enum('NONE', 'LOW', 'MEDIUM', 'HIGH', name='allergenrisk'), nullable=False),
    sa.Column('maintenance_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='maintenancelevel'), nullable=False),
    sa.Column('growth_rate', sa.Enum('SLOW', 'MODERATE', 'FAST', name='growthrate'), nullable=False),
    sa.Column('space_type_compatibility', postgresql.ARRAY(sa.Enum('INDOOR', 'OUTDOOR_BALCONY', 'OUTDOOR_GARDEN', 'PUBLIC_PARK', name='spacetype')), nullable=False),
    sa.Column('temperature_range', sa.String(), nullable=True),
    sa.Column('soil_ph_range', sa.String(), nullable=True),
    sa.Column('seasonal_allergen_modifier', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scientific_name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lng', sa.Float(), nullable=True),
    sa.Column('device_fingerprint', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('community_drives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organizer_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('location_center', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('geofence_polygon', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('radius_meters', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('participant_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('species_id', sa.UUID(), nullable=False),
    sa.Column('scan_id', sa.String(length=20), nullable=False),
    sa.Column('common_name', sa.String(), nullable=True),
    sa.Column('registered_location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('anchor_location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('planting_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('space_type', sa.Enum('INDOOR', 'OUTDOOR_BALCONY', 'OUTDOOR_GARDEN', 'PUBLIC_PARK', name='spacetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['species_id'], ['plant_species.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id')
    )
    op.create_table('drive_participations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('drive_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drive_id'], ['community_drives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'drive_id', name='uq_user_drive')
    )
    op.create_table('growth_updates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plant_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('submitted_gps', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('exif_gps', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('server_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', 'MANUAL_REVIEW', name='verificationstatus'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('cv_model_version', sa.String(), nullable=True),
    sa.Column('growth_stage_label', sa.String(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_growth_updates_plant_id_timestamp', 'growth_updates', ['plant_id', 'server_timestamp'], unique=False)
    op.create_table('reward_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plant_id', sa.UUID(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('trigger_event', sa.String(), nullable=False),
    sa.Column('balance_snapshot', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('balance_snapshot >= 0', name='check_balance_snapshot_non_negative'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reward_transactions_user_id_created_at', 'reward_transactions', ['user_id', 'created_at'], unique=False)
    op.execute("""
    CREATE OR REPLACE FUNCTION prevent_modify_append_only()
    RETURNS trigger AS $$
    BEGIN
        RAISE EXCEPTION 'This table is append-only. Updates and Deletes are not allowed.';
    END;
    $$ LANGUAGE plpgsql;
    """)

    op.execute("""
    CREATE TRIGGER growth_updates_append_only
        BEFORE UPDATE OR DELETE ON growth_updates
        FOR EACH ROW EXECUTE FUNCTION prevent_modify_append_only();
    """)

    op.execute("""
    CREATE TRIGGER reward_transactions_append_only
        BEFORE UPDATE OR DELETE ON reward_transactions
        FOR EACH ROW EXECUTE FUNCTION prevent_modify_append_only();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS reward_transactions_append_only ON reward_transactions")
    op.execute("DROP TRIGGER IF EXISTS growth_updates_append_only ON growth_updates")
    op.execute("DROP FUNCTION IF EXISTS prevent_modify_append_only()")
    op.drop_index('ix_reward_transactions_user_id_created_at', table_name='reward_transactions')
    op.drop_table('reward_transactions')
    op.drop_index('ix_growth_updates_plant_id_timestamp', table_name='growth_updates')
    op.drop_table('growth_updates')
    op.drop_table('drive_participations')
    op.drop_table('plants')
    op.drop_table('community_drives')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('plant_species')
    op.drop_table('news_feed_items')
    op.drop_index('ix_environmental_profiles_location_tile', table_name='environmental_profiles')
    op.drop_table('environmental_profiles')
    # ### end Alembic commands ###
